### ISSUE TITLE
filter_horizontal not supported

### ISSUE THREAD

**Issue by khaled-hayek** [app-generator/django-admin-soft-dashboard#8]
I added the UI soft dashboard theme to my project which has M2M relation and in admin I added to the ModelAdmin class the filter_horizontal which will help to select the items as the following photo. But this is not exist in the theme.
<img width="841" alt="72eOv" src="https://user-images.githubusercontent.com/3869302/229061459-18f2a1d4-58b3-46a1-b8b5-d97903851968.png">

**Comment by app-generator** [comment]
Hello @mominur-helios, 

Please take a look at this `use case` that might relate to #9 

ty!

**Comment by mominur-helios** [comment]
Hello @khaled-hayek,
Can you please pull the latest changes. This issue is already fixed.

**Comment by app-generator** [comment]
Hello @khaled-hayek,
Make sure you're using the latest version `1.0.10` and let us know if the issue is still there. 

ty!
