### ISSUE TITLE
Support nested admin Lib

### ISSUE THREAD

**Issue by khaled-hayek** [app-generator/django-admin-soft-dashboard#9]
I would like to keep using the nestred admin lib even when I use the UI soft dashboard. Which is helping alot in orgnizing the inlines.
Here is the link to the lib:
https://django-nested-admin.readthedocs.io/en/latest/quickstart.html

**Comment by app-generator** [comment]
Hello @khaled-hayek 

Please use the latest version `v1.0.11`.
